version: "2.0"
services:
  web:
    build: docker/.
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongodb:/data/db
